#pragma once

#include <string>
#include <vector>
#include <Eigen/Dense>

namespace placo::problem
{
/**
 * @brief Elimination of hard equality constraints \f$ A x + b = 0 \f$ exploiting their structural sparsity.
 *
 * Some variables (the pivots) are expressed as an affine function of the others (the free variables):
 * \f$ x_{pivots} = Z x_{free} + x_0 \f$
 *
 * Variables are eliminated block by block: a minimum-degree ordering on the graph of variables appearing together in
 * equalities decides which block goes first (for instance the limbs of a robot before its floating base), and each
 * block is eliminated with a small dense factorization, passing its remaining coupling to the next blocks. Without any
 * structure, this reduces to a single dense elimination.
 *
 * The ordering (symbolic analysis) only depends on the structure of the equalities, it is cached and recomputed only
 * when this structure changes.
 */
class SparseElimination
{
public:
  /**
   * @brief An equality A x[columns] + b = 0: the k-th column of A is the variable columns[k] (sorted)
   */
  struct Equality
  {
    const Eigen::Map<const Eigen::MatrixXd>* A;
    const Eigen::VectorXd* b;
    const std::vector<int>* columns;
  };

  /**
   * @brief Eliminates the given equalities, throws a QPError if they are not full rank
   *
   * Sparse elimination is not used (false is returned) when the equalities have no structure (all the constrained
   * variables are in a single block) or when a block is poorly conditioned: expressing some variables as a function
   * of others (rather than using an orthonormal basis, as a dense QR elimination does) would then amplify rounding
   * errors.
   *
   * @param n_variables number of variables
   * @param equalities equalities
   * @return true if the elimination was performed (else, a dense QR elimination should be used)
   */
  bool eliminate(int n_variables, const std::vector<Equality>& equalities);

  /**
   * @brief Eliminated variables, in the order of the rows of \ref Z
   */
  std::vector<int> pivots;

  /**
   * @brief Free variables (sorted), in the order of the columns of \ref Z
   */
  std::vector<int> free;

  /**
   * @brief Pivots as a function of free variables: x_pivots = Z x_free + x0
   */
  Eigen::MatrixXd Z;
  Eigen::VectorXd x0;

  /**
   * @brief Columns of \ref Z that are not zero, for each of its rows
   */
  std::vector<std::vector<int>> Z_columns;

  /**
   * @brief Number of elimination steps (blocks) of the last analysis
   */
  int steps_count() const;

  /**
   * @brief Blocks are merged with the block they are eliminated into while they have at most this number of
   * variables (fewer, larger dense factorizations)
   */
  int max_block_size = 16;

  /**
   * @brief Blocks whose pivots (smallest over largest) are below this ratio are considered poorly conditioned
   */
  double min_pivot_ratio = 1e-6;

  /**
   * @brief The elimination is declined when the Frobenius norm of \ref Z is above this value. The solutions are
   * parametrized as x = N x_free + [x0], N stacking the identity (free variables) and Z (eliminated variables): since
   * N^T N = I + Z^T Z, the condition number of N is at most sqrt(1 + ||Z||^2). A large Z (typically growing along a
   * chain of substitutions) would make the reduced problem poorly conditioned, compared to the orthonormal basis of the
   * QR elimination.
   */
  double max_Z_norm = 100.;

  /**
   * @brief Frobenius norm of \ref Z for the last elimination (see \ref max_Z_norm)
   */
  double Z_norm = 0.;

  /**
   * @brief Outcome of the last elimination: "eliminated", or the reason why it was declined: "no_structure" (a single
   * block), "poorly_conditioned_block" (see \ref min_pivot_ratio) or "large_Z" (see \ref max_Z_norm)
   */
  std::string status;

protected:
  /**
   * @brief An elimination step: the block of variables eliminated, the variables they are coupled with and the
   * equalities involved (indices of the given equalities, or n_equalities + i for the rows generated by step i)
   */
  struct Step
  {
    std::vector<int> block;
    std::vector<int> separator;
    std::vector<int> factors;
  };

  /**
   * @brief Structural symbolic analysis: computes the elimination steps from the columns of the equalities
   */
  void analyze(int n_variables, const std::vector<std::vector<int>>& supports);

  std::vector<Step> steps;

  /**
   * @brief Structure used for the last analysis: number of variables, then for each equality its rows count, number
   * of columns and columns
   */
  std::vector<int> analyzed_structure;

  /**
   * @brief Columns of each equality (for the last analysis)
   */
  std::vector<std::vector<int>> supports;
};
}  // namespace placo::problem
