# Prefer an installed DAQP package; optionally build a checkout or fetch upstream.
set(DAQP_SOURCE_DIR "" CACHE PATH "Optional DAQP source checkout")
option(PLACO_FETCH_DAQP "Fetch DAQP when no installed package is found" ON)
set(DAQP_GIT_TAG "master" CACHE STRING "DAQP branch, tag, or commit to fetch")

if(DAQP_SOURCE_DIR)
  if(NOT EXISTS "${DAQP_SOURCE_DIR}/CMakeLists.txt")
    message(FATAL_ERROR "DAQP_SOURCE_DIR must point to a DAQP source checkout")
  endif()
  if(NOT TARGET daqp::daqp AND NOT TARGET daqp AND NOT TARGET DAQP::DAQP)
    add_subdirectory("${DAQP_SOURCE_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/daqp")
  endif()
else()
  # Upstream installs daqpConfig.cmake and currently exports unnamespaced targets.
  if(NOT TARGET daqp::daqp AND NOT TARGET daqp AND NOT TARGET DAQP::DAQP)
    find_package(daqp CONFIG QUIET)
  endif()
  if(NOT TARGET daqp::daqp AND NOT TARGET daqp AND NOT TARGET DAQP::DAQP)
    find_path(DAQP_INCLUDE_DIR NAMES daqp/api.h)
    find_library(DAQP_LIBRARY NAMES daqp)
    if(DAQP_INCLUDE_DIR AND DAQP_LIBRARY)
      add_library(DAQP::DAQP UNKNOWN IMPORTED)
      set_target_properties(DAQP::DAQP PROPERTIES
        IMPORTED_LOCATION "${DAQP_LIBRARY}"
        INTERFACE_INCLUDE_DIRECTORIES "${DAQP_INCLUDE_DIR}")
    elseif(PLACO_FETCH_DAQP)
      include(FetchContent)
      FetchContent_Declare(placo_daqp
        GIT_REPOSITORY https://github.com/darnstrom/daqp.git
        GIT_TAG "${DAQP_GIT_TAG}")
      FetchContent_MakeAvailable(placo_daqp)
      set(DAQP_SOURCE_DIR "${placo_daqp_SOURCE_DIR}")
    endif()
  endif()
endif()

if(NOT TARGET DAQP::DAQP)
  if(TARGET daqp::daqp)
    set(_daqptarget daqp::daqp)
  elseif(TARGET daqp)
    set(_daqptarget daqp)
  endif()
  if(_daqptarget)
    add_library(DAQP::DAQP INTERFACE IMPORTED)
    target_link_libraries(DAQP::DAQP INTERFACE "${_daqptarget}")
    # Upstream's build tree exposes include/api.h; its install tree exposes
    # include/daqp/api.h. Stage headers to give consumers one spelling in both.
    if(DAQP_SOURCE_DIR)
      set(_daqpheaders "${CMAKE_CURRENT_BINARY_DIR}/daqp_headers")
      file(MAKE_DIRECTORY "${_daqpheaders}/daqp")
      file(GLOB _daqp_header_files CONFIGURE_DEPENDS "${DAQP_SOURCE_DIR}/include/*.h")
      foreach(_header IN LISTS _daqp_header_files)
        get_filename_component(_name "${_header}" NAME)
        configure_file("${_header}" "${_daqpheaders}/daqp/${_name}" COPYONLY)
      endforeach()
      target_include_directories(DAQP::DAQP INTERFACE "${_daqpheaders}")
    endif()
  endif()
endif()

if(TARGET DAQP::DAQP)
  set(DAQP_AVAILABLE TRUE)
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DAQP REQUIRED_VARS DAQP_AVAILABLE)
mark_as_advanced(DAQP_INCLUDE_DIR DAQP_LIBRARY)
unset(_daqptarget)
unset(_daqpheaders)
unset(_daqp_header_files)
unset(_header)
unset(_name)
